name: The Morry Method
favicon: null
layout_spectrum: 0.7120190719142556
typography_spectrum: 0.4660707041621208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#215a8c'
    - '#ffffff'
    - '#ff6329'
    - '#42a0f2'
  brandStrength: 0.33797474089078605
  lightness: 0.6717719053849578
  saturation: 0.07341943751089275
  rhythmicContrast: 0.7677388284355402
purpose: []
