name: The Morry Method
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5038
title: The Morry Methjod
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c9cbdd'
    - '#728395'
    - '#1e2e2e'
  brandStrength: 0.33797474089078605
  lightness: 0.6717719053849578
  saturation: 0.07341943751089275
  rhythmicContrast: 0.7677388284355402
purpose: []
